### ISSUE TITLE
Ending order process after no evaluation is selected

### ISSUE THREAD

**Issue by Iliricon** [d120/pyfeedback#7]
Remarks by Prof. Goesele:

Guten Tag,

noch ein Punkt: Wenn man die LV nicht evaluieren will (so wie hier beim Praktikum in der Lehre), muss man trotzdem die weiteren Schritte ausfüllen. Kann man das abstellen?

If the option to evaluate is deselected in /feedback/veranstalter/, no further pages should be shown to the user.

**Comment by ckleemann** [comment]
This is now pressend in the order-wizard branch
