### ISSUE TITLE
Semester hat einen Status

### ISSUE THREAD

**Issue by ckleemann** [d120/pyfeedback#72]
Mehr Support für uns: Das Semester bekommt einen Status der die Phase repräsentiert. Also "Bestellphase, drucken, Eva Woche". Dann sollen beim Status wechseln z.b. Bestellung zu drucken die Bestellung abgeschaltet werden.

Außerdem folgende Daten ergänzen:

* Datum der Erhebungswoche
* Deadline für die Dozentenbestellung 
Trac: 1203

**Comment by miterion** [comment]
Bereits länger implementiert
