### ISSUE TITLE
Seminare und Praktika Erhebungstermin besser erklären

### ISSUE THREAD

**Issue by ckleemann** [d120/pyfeedback#78]
Damit solche Missverständnisse wie hier nicht mehr entstehen:

​https://www.fachschaft.informatik.tu-darmstadt.de/mailman/private/feedback/2016-January/004446.html

Trac: 1357

**Comment by miterion** [comment]
Das Auswertungsdatum wird inzwischen klarer kommuniziert und ist auch nicht mehr fakultativ.
