### ISSUE TITLE
Sondererhebungen über pyFeedback abwickeln

### ISSUE THREAD

**Issue by ckleemann** [d120/pyfeedback#87]
Die Sondererhebungen für die Ophase und das Mentorenssystem sollen auch über pyFeedback abgewickelt werden. Vor allem soll der XML Export diese Erhebungen enthalten. Für das Mentorensystem ist die Bestellung über das System ebenfalls sinnvoll.

Da die Veranstaltungen mit anderen Bögen arbeiten muss die Software dafür angepasst werden und eine manuelle Anlegung der Veranstaltungen in pyFeedback ermöglichen.

Trac: 1447

**Comment by miterion** [comment]
Nur noch wenig Sondererhebungen aktuell, Modellierung in pyfeedback lohnt sich daher nur bedingt
