### ISSUE TITLE
CSV Import an XML Lehrveranstaltungsnummer anpassen 

### ISSUE THREAD

**Issue by ckleemann** [d120/pyfeedback#93]
Seit der Umstellung auf den XML Export um die Veranstaltungen in EvaSys anzulegen ist die Veranstaltungsnummer die wir an EvaSys übergeben nicht nur die Veranstaltungsnummer sondern enthält auch das aktuelle Semester. Hintergrund: EvaSys hat gemeckert das zwei mal eine Veranstaltung mit der gleichen Veranstaltungsnummer anlegen wollten.

Diese neue Veranstaltungsnummer wird noch nicht beim Import des Ergebnis CSV beachtet weshalb wir für jede Veranstaltung eine xyz hat in der Datenbank die Lehrveranstaltungsnummer abc in der CSV-Datei aber abc-semester Die Ergebnisse wurden trotzdem importiert. Fehlermeldung bekommen

Trac: 1282

**Comment by miterion** [comment]
Wurde behoben
