### ISSUE TITLE
Kritierien für den Feedbackpreis Beste Übung / Betreuung

### ISSUE THREAD

**Issue by ckleemann** [d120/pyfeedback#98]
Diese Fragen sollten für den Preis herangezogen werden:
3_1, 3_2, 3_3, 3_4, 3_5, 3_7, 4_1, 4_2, 4_3, 4_4, 4_5,6_3

Gitlab 23

**Comment by miterion** [comment]
Done in e16e59e27dea83fd7e7f73219727440bac31f5fd
